//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuelaWebApp.Models
{
    using System;
    
    public partial class crearCliente
    {
        public string usuario { get; set; }
        public string nombre { get; set; }
        public string clave { get; set; }
        public string pasaporte { get; set; }
        public string correo { get; set; }
        public int paisResidencia { get; set; }
    }
}
