//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuelaWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineavuelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lineavuelo()
        {
            this.pase = new HashSet<pase>();
            this.equipaje = new HashSet<equipaje>();
        }
    
        public int idlineavuelo { get; set; }
        public int idvuelo { get; set; }
        public System.DateTime horapartida { get; set; }
        public System.DateTime horallegada { get; set; }
        public Nullable<decimal> cantescalas { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual vuelo vuelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pase> pase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipaje> equipaje { get; set; }
    }
}
