//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuelaWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pase
    {
        public int idpase { get; set; }
        public int idlineavuelo { get; set; }
        public string numeroasiento { get; set; }
        public string pasaporte { get; set; }
        public Nullable<bool> usado { get; set; }
    
        public virtual lineavuelo lineavuelo { get; set; }
    }
}
